### ISSUE TITLE
upload package to PyPI

### ISSUE THREAD

**Issue by dlyongemallo** [dlyongemallo/qiskit-zx-transpiler#25]
Request is for uploading the transpiler as a package to [PyPI](https://pypi.org/) so it can be installed using pip.

**Comment by 1ucian0** [comment]
as part of this process, can it be exposed as a plugin? https://docs.quantum.ibm.com/transpile/create-a-transpiler-plugin

**Comment by dlyongemallo** [comment]
Yes, certainly.

**Comment by dlyongemallo** [comment]
Package has been uploaded to PyPI ([link](https://pypi.org/project/qiskit-zx-transpiler/)) and also exposed as a Qiskit transpiler plugin.
