### ISSUE TITLE
Transpiler optimization_method="zxpass" gives wrong result 

### ISSUE THREAD

**Issue by BankNatchapol** [dlyongemallo/qiskit-zx-transpiler#44]
### Environment

- **Qiskit version**:  1.1.0
- **Python version**:  3.10.12
- **Operating system**: Google Colab

### What is happening?

Circuits after Transpilation should give similar result, but not.

### How can we reproduce the issue?

```
from qiskit.quantum_info import Statevector
from qiskit.compiler import transpile

with open('acircuit.qpy', 'rb') as handle:
    qc = qpy.load(handle)
wo = transpile(qc, basis_gates=['cz', 'swap', 'cx', 'tdg', 's', 'sdg', 'h', 'rz'], optimization_level=1)[0]
w = transpile(wo, basis_gates=['cz', 'swap', 'cx', 'tdg', 's', 'sdg', 'h', 'rz'], optimization_method="zxpass")

print(Statevector(wo))
print(Statevector(w))
```
ill attach `acircuit.qpy`
[acircuit.zip](https://github.com/user-attachments/files/15746610/acircuit.zip)

### What should happen?

the statevector should be the same.

### Any suggestions?

If it's correct, please guide me how to make the statevector output to be the same. Thank you in advance.

**Comment by dlyongemallo** [comment]
The state vectors produced by your program appear to be equivalent.

What's the output of the following for you?

```python
print(Statevector(wo).equiv(Statevector(w)))
```

This results in the output `True` for me.

**Comment by dlyongemallo** [comment]
@BankNatchapol Can this issue be closed?

**Comment by dlyongemallo** [comment]
I'm going to close this issue as your repro case works perfectly fine for me. Please let me know if there's anything that's unclear or I could help you with.
